{
 "title": "BONUS_DASH",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "mynode_cpu_time", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "RAM Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "mynode_free_ram", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "HDD_SPACE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    { "expr": "mynode_hdd_space", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}