{
 "title": "Demo dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "HTTPS stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TOP 3 RATES",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(3, sum by(path, method) (rate(demo_api_request_duration_seconds_count[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95th percentile request latency",
   "type": "timeseries",
   "description": "HI HO",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path, method) (rate(demo_api_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{path}} - {{method}}"
    }
   ]
  },
  { "title": "CPU Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU USAGE",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum by(instance) (rate(demo_cpu_usage_seconds_total{mode!=\"idle\"}[5m]))\n/\n on(instance) group_left() demo_num_cpus",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}