{
 "title": "Monitoring 2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "HDD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FREE SPACE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/vda1\", mountpoint=\"/etc/resolv.conf\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "IO operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"vda\"}[$__rate_interval]) + rate(node_disk_written_bytes_total{device=\"vda\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[15s])) *100 )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVAILABLE RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}